name: Back - CI/CD Workflow 

on: 
  push:
    branches: 
      - develop
    paths:
      - 'back/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'back/**'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file back/pom.xml
      
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: back/target/site/jacoco